// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int countBigger = 0;
		int countSmaller = 0;

		for (int i = N; i > 0; i--){
			double random = Math.random();
			if (random > 0.5) {
				countBigger++;
			} else{
				countSmaller++;
			}
		}

		System.out.println("> 0.5:  " + countBigger + " times");
		System.out.println("<= 0.5: " + countSmaller + " times");

		if (countBigger > 0 && countSmaller > 0){
			double ratio = (double)Math.min(countSmaller, countBigger) / (double)Math.max(countSmaller, countBigger);
			System.out.println("Ratio:  " + ratio);
		}
	}
}
